echo ""
echo " _____________________________________________________"
echo " |          Lista de comandos possiveis:               |"
echo " |  |--------------------------------------------|     |"
echo " |  | -> i nomeArtigo preço                      |     |"
echo " |  | Adicionar Artigo                           |     |"
echo " |  |--------------------------------------------|     |"
echo " |  | -> n códigoArtigo nomeArtigo               |     |"
echo " |  | Alterar o nome do Artigo                   |     |"
echo " |  |--------------------------------------------|     |"
echo " |  | -> p códigoArtigo preço                    |     |"
echo " |  | Alterar preço do Artigo                    |     |"
echo " |  |--------------------------------------------|     |"
echo " |  | -> a                                       |     |"
echo " |  | Executar agregação                         |     |"
echo " |  |--------------------------------------------|     |"
echo " |_____________________________________________________|"
echo ""

./ma